name: Build and Deploy
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Apply patch to submodule
        run: |
          cd themes/PaperModX
          git apply ../../patchs/themeX.diff
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'v0.128.0'
          extended: true
      - name: Build
        run: |
          hugo \
            --gc --enableGitInfo
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
